export const avatar: string;
export const container: string;
export const dialogSubtitle: string;
export const dialogTitle: string;
export const dialogTitleDetails: string;
export const profileImageContainer: string;
export const userCaption: string;
export const userLastMessage: string;
export const userTitle: string;
